### ISSUE TITLE
Missing .metas

### ISSUE THREAD

**Issue by stefanhacks** [PauloPhenee/WildRose#1]
Hello PauloPhenee, thank you for submitting the challenge!

I've been reviewing your code but unable to import your project successfully. From what I've gathered, it seems to be because you have not committed your **.meta files** to the repository.

That's a common mistake, they do seem unimportant, but although regenerated by cocos they hold assets and prefab information needed to reimport the project without errors. Would you mind uploading them so I can continue the review process?

Thanks!

**Comment by PauloPhenee** [comment]
Hi, sorry about that, I had just copied from one repository to another (I
had saved in Azure first) without opening the second instance so it didn't
generate the meta. All good now.
Thanks!

Em ter., 19 de jan. de 2021 às 10:30, Filipe Stefano <
notifications@github.com> escreveu:

**Comment by PauloPhenee** [comment]
Ok, it was actually an error on the gitignore, meta was included on the
ignore list, fixed it.

Em ter., 19 de jan. de 2021 às 11:40, Paulo Silva <paulo.phenee@gmail.com>
escreveu:

**Comment by stefanhacks** [comment]
Thanks for the quick response! Managed to work just fine now.
